spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-update
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api