server:
  port: 80
  tomcat:
   uri-encoding: UTF-8
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-update
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api