spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api