server:
  port: 80
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create-update
  datasource:
    url: "jdbc:mysql://localhost:3306/ptm"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api